twig:
    default_path: '%kernel.project_dir%/templates'
    
    globals:
        azuracom_api_url: "%env(resolve:AZURACOM_API_URL)%"
        client_context: '@App\Context\ClientContext'

when@test:
    twig:
        strict_variables: true